### ISSUE TITLE
The target pod affinity setting in tutorials cannot work

### ISSUE THREAD

**Issue by von1994** [openebs/jiva-operator#124]
**What steps did you take and what happened:**
I created an example jivavolumespolicy as policies.md wrote.But target  pod affinity setting didn't work even get empty when I get jivavolumespolicy from server.

**What did you expect to happen:**
The target  pod affinity setting works.

**Anything else you would like to add:**
I think this is one mistake in docs. The filed of affinity.fields must be one of nodeAffinity,podAffinity,podAntiAffinity,the requiredDuringSchedulingIgnoredDuringExecution is subfield.

**Environment:**
- Jiva version
- OpenEBS version
- Kubernetes version (use `kubectl version`): v1.20.1
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by shubham14bajpai** [comment]
This issue has been fixed by the above PRs.
