### ISSUE TITLE
Move jivaVolume and jivaVolumePolicy CRDs to v1

### ISSUE THREAD

**Issue by shubham14bajpai** [openebs/jiva-operator#160]
**Describe the problem/challenge you have**

The CRDs for [`jivaVolume`](https://github.com/openebs/jiva-operator/blob/develop/pkg/apis/openebs/v1alpha1/jivavolume_types.go) and [`jivaVolumePolicy`](https://github.com/openebs/jiva-operator/blob/develop/pkg/apis/openebs/v1alpha1/jivavolumepolicy_types.go) are still in v1alpha1 can be moved to v1 version to mark jiva-operator as stable.

**Describe the solution you'd like**

As the specs for the CRDs are now stable and no more changes to the spec are coming we can safely add the v1 CRDs. And we can still query the v1alpha1 CRDs via v1 version. Since schema is same for both, using conversion strategy as none. Ref the PR https://github.com/openebs/zfs-localpv/pull/140 for help :slightly_smiling_face: 

**Anything else you would like to add:**

Please verify the upgrade scenario where the v1alpha1 CRs are getting synced after migrating to v1.

**Comment by devkapilbansal** [comment]
Hi @shubham14bajpai I would be interested in picking this issue.

**Comment by shubham14bajpai** [comment]
@devkapilbansal Sure, feel free to make a PR.

**Comment by shubham14bajpai** [comment]
Hi @devkapilbansal Just checking in, did you get a chance to work on this? If any help is needed you can ask here or ping us on kubernetes #openebs-dev channel.
