### ISSUE TITLE
how-to guide on recovering data

### ISSUE THREAD

**Issue by rbadillo** [openebs/jiva-operator#211]
**What steps did you take and what happened:**

I would like to know if there is a guide to recover data on several PV using Jiva Operator after the openebs namespace was deleted by mistake.

**What did you expect to happen:**
Reinstalling openebs and be able to re-use the existing PV and PVCs.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs <jiva-operator pod name> -n openebs` (optional)
* `kubectl get jv <jiva volume cr name> -n openebs -o yaml`
* `kubectl get jvp <jiva volume policy> -n openebs -o yaml`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- Jiva version:
2.12.2

- OpenEBS version:

- Kubernetes version (use `kubectl version`):
Server and Client: 1.22

- Kubernetes installer & version:
microk8s

- Cloud provider or hardware configuration:
Custom Hardware (Linux)

- OS (e.g. from `/etc/os-release`):
Ubuntu 20.04.3 LTS

**Comment by niladrih** [comment]
@rbadillo and I got into a meeting... the output of `k get pv` showed that an NFS volume and it's backing Jiva volume were both in 'Released' state. The underlying Hostpath volumes (for the Jiva CSI volume) were also deleted. The JivaVolume CR was also missing got the Jiva PV. The data for the volume could not be recovered by reinstating the iSCSI target, replica controllers and the JivaVolume CR as the underlying hostpath volumes were deleted.
